FROM golang:alpine AS build

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/main.go

FROM alpine:latest AS runtime


WORKDIR /app
COPY --from=builder /app/main .

EXPOSE 8080
CMD ["./main"]

